"""Schema and repository functions — dual-backend (SQLite + Postgres).

Tables mirror the pydantic models in models.py, plus `runs` (reproducibility),
`judge_calls` (token/cost audit — every LLM call is logged, §6.2 / CLAUDE.md),
and `jobs` (the web layer's async queue). See §4, §5 of CITEWORTHY_SPEC.md.

The CLI and tests use SQLite; the web app + worker use Postgres (Neon/Supabase)
by setting CITEWORTHY_DATABASE_URL. A thin `Store` proxy hides the DB-API
differences (placeholder style, autoincrement) so every repository function below
is written once and runs on either backend.
"""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import datetime
from pathlib import Path

from .models import (
    CitationObservation,
    Matchup,
    Passage,
    RankResult,
    Run,
    TargetQuery,
)

DEFAULT_DB_PATH = Path("citeworthy.db")

# Autoincrement PK differs by dialect; everything else in the schema is portable
# (TEXT/INTEGER/REAL, CHECK, ON CONFLICT are all supported on both backends).
_AUTOPK = {
    "sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "postgres": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
}

SCHEMA_TEMPLATE = """
CREATE TABLE IF NOT EXISTS queries (
    id        TEXT PRIMARY KEY,
    text      TEXT NOT NULL,
    our_url   TEXT,
    tier      TEXT NOT NULL CHECK (tier IN ('money', 'supporting'))
);

CREATE TABLE IF NOT EXISTS runs (
    run_id      TEXT PRIMARY KEY,
    kind        TEXT NOT NULL CHECK (kind IN ('rank', 'optimize', 'track')),
    started_at  TEXT NOT NULL,
    config_hash TEXT NOT NULL,
    git_sha     TEXT
);

CREATE TABLE IF NOT EXISTS passages (
    id            TEXT PRIMARY KEY,
    url           TEXT NOT NULL,
    domain        TEXT NOT NULL,
    title         TEXT NOT NULL,
    chunk_index   INTEGER NOT NULL,
    text          TEXT NOT NULL,
    is_ours       INTEGER NOT NULL DEFAULT 0,
    variant_of    TEXT,
    variant_label TEXT
);

CREATE TABLE IF NOT EXISTS matchups (
    id             {autopk},
    run_id         TEXT NOT NULL,
    query_id       TEXT NOT NULL,
    passage_a      TEXT NOT NULL,
    passage_b      TEXT NOT NULL,
    winner         TEXT NOT NULL,
    reason_code    TEXT NOT NULL,
    reason_text    TEXT NOT NULL,
    judge_model    TEXT NOT NULL,
    position_order TEXT NOT NULL CHECK (position_order IN ('ab', 'ba')),
    sample_index   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS rank_results (
    run_id         TEXT NOT NULL,
    query_id       TEXT NOT NULL,
    passage_id     TEXT NOT NULL,
    bt_strength    REAL NOT NULL,
    selection_prob REAL NOT NULL,
    rank           INTEGER NOT NULL,
    ci_low         REAL NOT NULL,
    ci_high        REAL NOT NULL,
    PRIMARY KEY (run_id, passage_id)
);

CREATE TABLE IF NOT EXISTS observations (
    run_id           TEXT NOT NULL,
    query_id         TEXT NOT NULL,
    engine           TEXT NOT NULL CHECK (engine IN ('perplexity', 'gemini_grounded')),
    sample_index     INTEGER NOT NULL,
    cited_urls       TEXT NOT NULL,   -- JSON array
    answer_text_hash TEXT NOT NULL,
    observed_at      TEXT NOT NULL
);

-- Token/cost audit for every LLM call, for `citeworthy costs` and budget caps.
CREATE TABLE IF NOT EXISTS judge_calls (
    id            {autopk},
    run_id        TEXT NOT NULL,
    model         TEXT NOT NULL,
    input_tokens  INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    est_usd       REAL NOT NULL,
    created_at    TEXT NOT NULL
);

-- Async job queue for the web layer: the API enqueues, the worker processes.
CREATE TABLE IF NOT EXISTS jobs (
    id              {autopk},
    job_id          TEXT NOT NULL UNIQUE,
    kind            TEXT NOT NULL CHECK (kind IN ('rank', 'optimize', 'track')),
    query_id        TEXT,
    status          TEXT NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued', 'running', 'done', 'error')),
    run_id          TEXT,
    report_query_id TEXT,
    error           TEXT,
    created_at      TEXT NOT NULL,
    started_at      TEXT,
    finished_at     TEXT
);
"""


class Store:
    """Thin proxy over a DB-API connection that normalises dialect differences.

    Repository functions use `?` placeholders and standard SQL; the proxy
    rewrites `?` -> `%s` for Postgres. `execute` returns the driver cursor, so
    `.fetchall()/.fetchone()/.rowcount` work as on sqlite3."""

    def __init__(self, raw, dialect: str) -> None:
        self._raw = raw
        self.dialect = dialect

    def execute(self, sql: str, params=()):
        if self.dialect == "postgres":
            sql = sql.replace("?", "%s")
        return self._raw.execute(sql, params)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()

    @property
    def raw(self):
        return self._raw


def _resolve_target(target: str | Path | None) -> tuple[str, str]:
    """Return (dialect, dsn). A postgres URL selects Postgres; anything else is a
    SQLite file path. Defaults to CITEWORTHY_DATABASE_URL, then citeworthy.db."""
    if target is None:
        target = os.environ.get("CITEWORTHY_DATABASE_URL") or DEFAULT_DB_PATH
    s = str(target)
    if s.startswith(("postgres://", "postgresql://")):
        return "postgres", s
    return "sqlite", s


def connect(target: str | Path | None = None) -> Store:
    dialect, dsn = _resolve_target(target)
    if dialect == "postgres":
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(dsn, row_factory=dict_row, autocommit=False)
        return Store(raw, "postgres")

    raw = sqlite3.connect(dsn)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys = ON")
    return Store(raw, "sqlite")


def ensure_schema(store: Store) -> None:
    """Create all tables if they don't exist, on an open Store."""
    schema = SCHEMA_TEMPLATE.format(autopk=_AUTOPK[store.dialect])
    for statement in filter(str.strip, schema.split(";")):
        store.execute(statement)
    store.commit()


def init_db(target: str | Path | None = None) -> str:
    """Create all tables if they don't exist; return the resolved DSN/path."""
    store = connect(target)
    try:
        ensure_schema(store)
    finally:
        store.close()
    return _resolve_target(target)[1]


# --- Repository functions --------------------------------------------------
# Milestone 1 covers query management (used by `queries add|list|rm`) and run
# creation. Persistence for passages/matchups/results/observations is scaffolded
# and lands with the milestone that produces that data.


def upsert_query(conn: Store, q: TargetQuery) -> None:
    conn.execute(
        """
        INSERT INTO queries (id, text, our_url, tier)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            text = excluded.text,
            our_url = excluded.our_url,
            tier = excluded.tier
        """,
        (q.id, q.text, str(q.our_url) if q.our_url else None, q.tier),
    )
    conn.commit()


def list_queries(conn: Store) -> list[TargetQuery]:
    rows = conn.execute("SELECT id, text, our_url, tier FROM queries ORDER BY id").fetchall()
    return [
        TargetQuery(
            id=r["id"],
            text=r["text"],
            our_url=r["our_url"],
            tier=r["tier"],
        )
        for r in rows
    ]


def get_query(conn: Store, query_id: str) -> TargetQuery | None:
    r = conn.execute(
        "SELECT id, text, our_url, tier FROM queries WHERE id = ?", (query_id,)
    ).fetchone()
    if r is None:
        return None
    return TargetQuery(id=r["id"], text=r["text"], our_url=r["our_url"], tier=r["tier"])


def remove_query(conn: Store, query_id: str) -> bool:
    cur = conn.execute("DELETE FROM queries WHERE id = ?", (query_id,))
    conn.commit()
    return cur.rowcount > 0


def create_run(conn: Store, run: Run) -> None:
    conn.execute(
        """
        INSERT INTO runs (run_id, kind, started_at, config_hash, git_sha)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            run.run_id,
            run.kind,
            run.started_at.isoformat(),
            run.config_hash,
            run.git_sha,
        ),
    )
    conn.commit()


def log_judge_call(
    conn: Store,
    run_id: str,
    model: str,
    input_tokens: int,
    output_tokens: int,
    est_usd: float,
    created_at: datetime,
) -> None:
    conn.execute(
        """
        INSERT INTO judge_calls
            (run_id, model, input_tokens, output_tokens, est_usd, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (run_id, model, input_tokens, output_tokens, est_usd, created_at.isoformat()),
    )
    conn.commit()


def cost_summary(conn: Store) -> list[dict]:
    """Aggregate logged token spend per model, for `citeworthy costs`."""
    rows = conn.execute(
        """
        SELECT model,
               COUNT(*)            AS calls,
               SUM(input_tokens)   AS input_tokens,
               SUM(output_tokens)  AS output_tokens,
               SUM(est_usd)        AS est_usd
        FROM judge_calls
        GROUP BY model
        ORDER BY est_usd DESC
        """
    ).fetchall()
    return [dict(r) for r in rows]


# --- Rank persistence (Milestone 4) ----------------------------------------


def save_passage(conn: Store, passage: Passage) -> None:
    conn.execute(
        """
        INSERT INTO passages
            (id, url, domain, title, chunk_index, text, is_ours, variant_of, variant_label)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            url = excluded.url, domain = excluded.domain, title = excluded.title,
            chunk_index = excluded.chunk_index, text = excluded.text,
            is_ours = excluded.is_ours, variant_of = excluded.variant_of,
            variant_label = excluded.variant_label
        """,
        (
            passage.id,
            str(passage.url),
            passage.domain,
            passage.title,
            passage.chunk_index,
            passage.text,
            int(passage.is_ours),
            passage.variant_of,
            passage.variant_label,
        ),
    )
    conn.commit()


def save_matchup(conn: Store, run_id: str, matchup: Matchup) -> None:
    conn.execute(
        """
        INSERT INTO matchups
            (run_id, query_id, passage_a, passage_b, winner, reason_code,
             reason_text, judge_model, position_order, sample_index)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            run_id,
            matchup.query_id,
            matchup.passage_a,
            matchup.passage_b,
            matchup.winner,
            matchup.reason_code,
            matchup.reason_text,
            matchup.judge_model,
            matchup.position_order,
            matchup.sample_index,
        ),
    )
    conn.commit()


def save_rank_result(conn: Store, result: RankResult) -> None:
    conn.execute(
        """
        INSERT INTO rank_results
            (run_id, query_id, passage_id, bt_strength, selection_prob, rank, ci_low, ci_high)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(run_id, passage_id) DO UPDATE SET
            query_id = excluded.query_id, bt_strength = excluded.bt_strength,
            selection_prob = excluded.selection_prob, rank = excluded.rank,
            ci_low = excluded.ci_low, ci_high = excluded.ci_high
        """,
        (
            result.run_id,
            result.query_id,
            result.passage_id,
            result.bt_strength,
            result.selection_prob,
            result.rank,
            result.ci_low,
            result.ci_high,
        ),
    )
    conn.commit()


def latest_rank_run_id(conn: Store, query_id: str) -> str | None:
    """The run_id of the most recent rank run that produced results for a query."""
    row = conn.execute(
        """
        SELECT rr.run_id
        FROM rank_results rr
        JOIN runs r ON rr.run_id = r.run_id
        WHERE rr.query_id = ?
        ORDER BY r.started_at DESC
        LIMIT 1
        """,
        (query_id,),
    ).fetchone()
    return row["run_id"] if row else None


def get_rank_results(
    conn: Store, run_id: str, query_id: str
) -> list[RankResult]:
    rows = conn.execute(
        """
        SELECT run_id, query_id, passage_id, bt_strength, selection_prob, rank, ci_low, ci_high
        FROM rank_results
        WHERE run_id = ? AND query_id = ?
        ORDER BY rank
        """,
        (run_id, query_id),
    ).fetchall()
    return [RankResult(**dict(r)) for r in rows]


def get_matchups(
    conn: Store, run_id: str, query_id: str
) -> list[Matchup]:
    rows = conn.execute(
        """
        SELECT query_id, passage_a, passage_b, winner, reason_code, reason_text,
               judge_model, position_order, sample_index
        FROM matchups
        WHERE run_id = ? AND query_id = ?
        """,
        (run_id, query_id),
    ).fetchall()
    return [Matchup(**dict(r)) for r in rows]


def get_passages(conn: Store, ids: list[str]) -> dict[str, Passage]:
    if not ids:
        return {}
    placeholders = ",".join("?" * len(ids))
    rows = conn.execute(
        f"""
        SELECT id, url, domain, title, chunk_index, text, is_ours, variant_of, variant_label
        FROM passages WHERE id IN ({placeholders})
        """,
        ids,
    ).fetchall()
    result: dict[str, Passage] = {}
    for r in rows:
        result[r["id"]] = Passage(
            id=r["id"],
            url=r["url"],
            domain=r["domain"],
            title=r["title"],
            chunk_index=r["chunk_index"],
            text=r["text"],
            is_ours=bool(r["is_ours"]),
            variant_of=r["variant_of"],
            variant_label=r["variant_label"],
        )
    return result


# --- Tracker persistence (Milestone 5) -------------------------------------


def save_observation(conn: Store, run_id: str, obs: CitationObservation) -> None:
    conn.execute(
        """
        INSERT INTO observations
            (run_id, query_id, engine, sample_index, cited_urls, answer_text_hash, observed_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            run_id,
            obs.query_id,
            obs.engine,
            obs.sample_index,
            json.dumps(obs.cited_urls),
            obs.answer_text_hash,
            obs.observed_at.isoformat(),
        ),
    )
    conn.commit()


def _row_to_observation(r: sqlite3.Row) -> tuple[str, CitationObservation]:
    """Returns (run_id, observation)."""
    return r["run_id"], CitationObservation(
        run_id=r["run_id"],
        query_id=r["query_id"],
        engine=r["engine"],
        sample_index=r["sample_index"],
        cited_urls=json.loads(r["cited_urls"]),
        answer_text_hash=r["answer_text_hash"],
        observed_at=datetime.fromisoformat(r["observed_at"]),
    )


def get_observations(
    conn: Store,
    *,
    query_id: str | None = None,
    engine: str | None = None,
    run_id: str | None = None,
) -> list[CitationObservation]:
    """Fetch observations (optionally filtered), oldest run first."""
    clauses, params = [], []
    if query_id is not None:
        clauses.append("o.query_id = ?")
        params.append(query_id)
    if engine is not None:
        clauses.append("o.engine = ?")
        params.append(engine)
    if run_id is not None:
        clauses.append("o.run_id = ?")
        params.append(run_id)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = conn.execute(
        f"""
        SELECT o.run_id, o.query_id, o.engine, o.sample_index, o.cited_urls,
               o.answer_text_hash, o.observed_at
        FROM observations o
        JOIN runs r ON o.run_id = r.run_id
        {where}
        ORDER BY r.started_at ASC, o.sample_index ASC
        """,
        params,
    ).fetchall()
    return [_row_to_observation(r)[1] for r in rows]


def observations_by_run(
    conn: Store, query_id: str, engine: str
) -> list[list[CitationObservation]]:
    """Observations for a (query, engine), grouped by run in chronological order
    — the shape the rolling-window / trend stats expect (§6.6)."""
    rows = conn.execute(
        """
        SELECT o.run_id, o.query_id, o.engine, o.sample_index, o.cited_urls,
               o.answer_text_hash, o.observed_at, r.started_at
        FROM observations o
        JOIN runs r ON o.run_id = r.run_id
        WHERE o.query_id = ? AND o.engine = ?
        ORDER BY r.started_at ASC, o.sample_index ASC
        """,
        (query_id, engine),
    ).fetchall()
    groups: list[list[CitationObservation]] = []
    order: list[str] = []
    by_run: dict[str, list[CitationObservation]] = {}
    for r in rows:
        run_id, obs = _row_to_observation(r)
        if run_id not in by_run:
            by_run[run_id] = []
            order.append(run_id)
        by_run[run_id].append(obs)
    for run_id in order:
        groups.append(by_run[run_id])
    return groups


def _dump_urls(urls: list[str]) -> str:
    return json.dumps(urls)


# --- Job queue (web layer) -------------------------------------------------
# The API enqueues jobs (fast); the worker claims and runs them (slow). Jobs are
# returned as plain dicts so the API can serialise them directly.


def enqueue_job(
    conn: Store, job_id: str, kind: str, query_id: str | None, created_at: datetime
) -> None:
    conn.execute(
        """
        INSERT INTO jobs (job_id, kind, query_id, status, created_at)
        VALUES (?, ?, ?, 'queued', ?)
        """,
        (job_id, kind, query_id, created_at.isoformat()),
    )
    conn.commit()


def get_job(conn: Store, job_id: str) -> dict | None:
    row = conn.execute(
        """
        SELECT job_id, kind, query_id, status, run_id, report_query_id, error,
               created_at, started_at, finished_at
        FROM jobs WHERE job_id = ?
        """,
        (job_id,),
    ).fetchone()
    return dict(row) if row else None


def list_jobs(conn: Store, limit: int = 50) -> list[dict]:
    rows = conn.execute(
        """
        SELECT job_id, kind, query_id, status, run_id, report_query_id, error,
               created_at, started_at, finished_at
        FROM jobs ORDER BY created_at DESC, id DESC LIMIT ?
        """,
        (limit,),
    ).fetchall()
    return [dict(r) for r in rows]


def claim_next_job(conn: Store, now: datetime) -> dict | None:
    """Atomically claim the oldest queued job and mark it running. Returns the
    claimed job dict, or None if the queue is empty / another worker won it."""
    row = conn.execute(
        "SELECT job_id FROM jobs WHERE status = 'queued' ORDER BY created_at ASC, id ASC LIMIT 1"
    ).fetchone()
    if row is None:
        return None
    job_id = row["job_id"]
    cur = conn.execute(
        "UPDATE jobs SET status = 'running', started_at = ? WHERE job_id = ? AND status = 'queued'",
        (now.isoformat(), job_id),
    )
    conn.commit()
    if getattr(cur, "rowcount", 0) == 0:
        return None  # lost the race to another worker
    return get_job(conn, job_id)


def finish_job(
    conn: Store,
    job_id: str,
    status: str,
    finished_at: datetime,
    *,
    run_id: str | None = None,
    report_query_id: str | None = None,
    error: str | None = None,
) -> None:
    conn.execute(
        """
        UPDATE jobs
        SET status = ?, run_id = ?, report_query_id = ?, error = ?, finished_at = ?
        WHERE job_id = ?
        """,
        (status, run_id, report_query_id, error, finished_at.isoformat(), job_id),
    )
    conn.commit()
